In [2]:
#3b
import numpy as np

# Generate random stock price matrices (5 days × 3 features)
stockA = np.random.randint(90, 120, (5,3))
stockB = np.random.randint(90, 120, (5,3))

print("Stock A Data:\n", stockA)
print("\nStock B Data:\n", stockB)

# Element-wise sum
sum_matrix = stockA + stockB

# Element-wise difference
diff_matrix = stockA - stockB

print("\nElement-wise Sum:\n", sum_matrix)
print("\nElement-wise Difference:\n", diff_matrix)

Stock A Data:
 [[116 110  94]
 [ 96  96  97]
 [110  96 115]
 [104 114 109]
 [104 108 113]]

Stock B Data:
 [[117  96  96]
 [108 108  91]
 [ 95 103  92]
 [ 96 117 115]
 [ 99  97  97]]

Element-wise Sum:
 [[233 206 190]
 [204 204 188]
 [205 199 207]
 [200 231 224]
 [203 205 210]]

Element-wise Difference:
 [[ -1  14  -2]
 [-12 -12   6]
 [ 15  -7  23]
 [  8  -3  -6]
 [  5  11  16]]
