In [1]:
#2b
#analyze of student grade 
import numpy as np

grades = np.random.randint(50, 100, size=(30,3))   # 30 students, 3 subjects, grades between 50 and 100

print("Grades Matrix:\n", grades)

print("Subject Average:", grades.mean(axis=0))
print("Highest Marks:", grades.max())
print("Lowest Marks:", grades.min())

total = grades.sum(axis=1)
top_student = total.argmax()

print("Top Student Index:", top_student)

Grades Matrix:
 [[52 96 71]
 [59 81 56]
 [67 90 85]
 [81 93 98]
 [73 56 99]
 [98 93 65]
 [76 66 88]
 [69 84 92]
 [53 84 70]
 [64 85 70]
 [67 98 69]
 [91 92 99]
 [53 85 64]
 [83 81 75]
 [67 77 98]
 [85 78 63]
 [70 65 53]
 [53 65 78]
 [53 81 72]
 [52 50 98]
 [61 52 67]
 [54 55 80]
 [78 78 54]
 [61 71 71]
 [81 88 97]
 [72 54 97]
 [76 51 65]
 [66 74 96]
 [51 63 50]
 [55 91 79]]
Subject Average: [67.36666667 75.9        77.3       ]
Highest Marks: 99
Lowest Marks: 50
Top Student Index: 11
